#ifndef CANFRAMEID_H
#define CANFRAMEID_H

// Vehicle CAN Bus
#define VEHICLE_SPEED   0x632
#define BATTERY_INFO   0x300
#define FIRST_CONTROLLER_INFO  0x601
#define SECOND_CONTROLLER_INFO  0x602
#define FIRST_BMS_INFO  0x300
#define SECOND_BMS_INFO  0x301
#define THIRD_BMS_INFO  0x6B1
#define ARDUINO_INFO  0x608








#endif // CANFRAMEID_H
